---
title: "CJXT53-54 6OHDA OField LDR, DLC output analysis, BL vs LD1"
author: "THC Cheung"
date: "`r format(Sys.time())`"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    number_sections: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, cache=FALSE}
options(scipen = 0, digits = 3) # set decimal points in output
```

```{r load_data, include = FALSE}
# make sure to select "Project Directory" as Knit directory in RStudio GUI

library(readr)
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)
source("./R/stats_summary.R")
source("./R/stats_funs.R")
source("./R/barplot_for_notebook.R")


## Folders
# my_work_folder <- "E:/TimCheung/Dropbox (Personal)/"
my_work_folder <- "C:/Users/timhc/Dropbox/"

proj_folder <- "/Work/DLC/Cir_Sq_OpField_v2-TC-2022-10-18/vid_analyse/DLC_bout_csv_output/"

file_path_BL_paired <- "/DLC-bout_CJXT53_54_Baseline-S4-paired.csv"
file_path_LD1_S1 <- "/DLC-bout_CJXT53_54_LD1-S1-paired.csv"
file_path_LD1_S5 <- "/DLC-bout_CJXT53_54_LD1-S5-paired.csv"

file_path_BL_paired <- paste0(my_work_folder, proj_folder, file_path_BL_paired)
file_path_LD1_S1 <- paste0(my_work_folder, proj_folder, file_path_LD1_S1)
file_path_LD1_S5 <- paste0(my_work_folder, proj_folder, file_path_LD1_S5)

# Read CSV to dataframe
data_BL_paired <- readr::read_csv(file_path_BL_paired) %>%
    tibble::add_column(sess_name = "BL_paired", sess = "BL", context = "paired")

data_LD1_S1 <- readr::read_csv(file_path_LD1_S1) %>%
    tibble::add_column(sess_name = "LD1_S1", sess = "LD1_S1", context = "paired")

data_LD1_S5 <- readr::read_csv(file_path_LD1_S5) %>%
    tibble::add_column(sess_name = "LD1_S5", sess = "LD1_S5", context = "paired")

data_combo <- dplyr::bind_rows(data_BL_paired, data_LD1_S1, data_LD1_S5)

# Re-order factors for plotting
my_col_factor <- c('MouseID', '6OHDA_side', 'sess_name', 'sess', 'context')
my_col_factor_order <- c('BL_paired', 'LD1_S1', 'LD1_S5')
data_combo[my_col_factor] <- lapply(data_combo[my_col_factor], factor)
data_combo <- data_combo %>%
    mutate(sess_name = forcats::fct_relevel(sess_name, my_col_factor_order))

# Pull out non-character columns (these are usually data variables) vs. character columns (these are usually factors)
my_col_char <- data_combo %>% dplyr::summarise_all(class) %>% stringr::str_detect("character|factor")
my_colnames_char <- colnames(data_combo[my_col_char])
my_colnames_non_char <- colnames(data_combo[!my_col_char])


```



``` {r plot_analyse_loop, fig.width=4, fig.height=3, echo=FALSE, message=FALSE, error=TRUE}

exclude_cw_ccw <- TRUE

my_curr_var <- 1

for (i in 1:length(my_colnames_non_char)) {

    # go thru each column variables
    my_colnames_test <- append(my_colnames_char, my_colnames_non_char[i])
    my_var <- my_colnames_non_char[i]
    data_test <- data_combo[my_colnames_test] %>% rename(var = all_of(my_var))

    contains_cw_ccw = stringr::str_detect(my_var, "cw_") | stringr::str_detect(my_var, "ccw_")
    if (exclude_cw_ccw & contains_cw_ccw) {
        next
    } else {

        # print(paste0(my_curr_var, ": ", my_var))
        cat("\n*****", my_curr_var, ":", my_var, "*****\n")

        # summarize
        by_sess_name_data_test <- data_test %>%
            group_by(sess_name) %>%
            calc_mean_sem()
        by_sess_name_data_test

        # plot graph
        my_plot <- nb_barplot(data_test, sess_name, var) +
            theme(axis.text.x = element_text(angle = 20, vjust = 0.8, hjust=0.8),
                  axis.title.x = element_blank(),
                  axis.title.y = element_blank(),
                  legend.position = "none") +
            ggtitle(my_var)
        print(my_plot)

        # repeated one-way ANOVA
        oneway_anova_wn(data_test, subID="MouseID", wn_factor="sess", btw_factor = NULL, depvar="var",
                        remove_NaN = TRUE)

        my_curr_var <- my_curr_var + 1
    }

}

```

