---
title: "CJXT53-54 6OHDA OField LDR, DLC output analysis, BL vs. LD1, timebins"
author: "THC Cheung"
date: "`r format(Sys.time())`"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    number_sections: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, cache=FALSE}
options(scipen = 0, digits = 3) # set decimal points in output
```

```{r load_data, include = FALSE}
# make sure to select "Project Directory" as Knit directory in RStudio GUI

## Setup
library(readr)
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)
library(RColorBrewer)
source("./R/stats_summary.R")
source("./R/stats_funs.R")
source("./R/quick_plot.R")


## Folders
my_work_folder <- "E:/TimCheung/Dropbox (Personal)/"
# my_work_folder <- "C:/Users/timhc/Dropbox/"

proj_folder <- "/Work/DLC/Cir_Sq_OpField_v2-TC-2022-10-18/vid_analyse/DLC_bout_csv_output/"

file_path_BL_paired <- "/DLC-bout_CJXT53_54_Baseline-S4-paired_timebins.csv"
file_path_probe_paired <- "/DLC-bout_CJXT53_54_Probe-S1-paired_timebins.csv"
file_path_LD1_S1 <- "/DLC-bout_CJXT53_54_LD1-S1-paired_timebins.csv"
file_path_LD1_S5 <- "/DLC-bout_CJXT53_54_LD1-S5-paired_timebins.csv"
file_path_BL_unpaired <- "/DLC-bout_CJXT53_54_Baseline-S4-unpaired_timebins.csv"
file_path_probe_unpaired <- "/DLC-bout_CJXT53_54_Probe-S1-unpaired_timebins.csv"

file_path_BL_paired <- paste0(my_work_folder, proj_folder, file_path_BL_paired)
file_path_probe_paired <- paste0(my_work_folder, proj_folder, file_path_probe_paired)
file_path_LD1_S1 <- paste0(my_work_folder, proj_folder, file_path_LD1_S1)
file_path_LD1_S5 <- paste0(my_work_folder, proj_folder, file_path_LD1_S5)
file_path_BL_unpaired <- paste0(my_work_folder, proj_folder, file_path_BL_unpaired)
file_path_probe_unpaired <- paste0(my_work_folder, proj_folder, file_path_probe_unpaired)

# Read CSV to dataframe
data_BL_paired <- readr::read_csv(file_path_BL_paired) %>%
    tibble::add_column(sess_name = "BL_paired", sess = "BL", context = "paired", .after = "6OHDA_side")

data_probe_paired <- readr::read_csv(file_path_probe_paired) %>%
    tibble::add_column(sess_name = "probe_S1_paired", sess = "probe_S1", context = "paired", .after = "6OHDA_side")

data_BL_unpaired <-  readr::read_csv(file_path_BL_unpaired) %>%
    tibble::add_column(sess_name = "BL_unpaired", sess = "BL", context = "unpaired", .after = "6OHDA_side")

data_probe_unpaired <-  readr::read_csv(file_path_probe_unpaired) %>%
    tibble::add_column(sess_name = "probe_S1_unpaired", sess = "probe_S1", context = "unpaired", .after = "6OHDA_side")

data_LD1_S1 <- readr::read_csv(file_path_LD1_S1) %>%
    tibble::add_column(sess_name = "LD1_S1", sess = "LD1_S1", context = "paired", .after = "6OHDA_side")

data_LD1_S5 <- readr::read_csv(file_path_LD1_S5) %>%
    tibble::add_column(sess_name = "LD1_S5", sess = "LD1_S5", context = "paired", .after = "6OHDA_side")

data_combo <- dplyr::bind_rows(data_BL_paired,
                               data_LD1_S1, data_LD1_S5)

data_combo <- data_combo %>%
    mutate(MouseID_sess_name = paste0(MouseID, "_", sess_name))

# Re-order factors for plotting
my_col_factor <- c('MouseID', '6OHDA_side', 'sess_name', 'sess', 'context', 'start_time_in_min', 'end_time_in_min')
my_col_factor_order <- c('BL_paired', 'LD1_S1', 'LD1_S5')
data_combo[my_col_factor] <- lapply(data_combo[my_col_factor], factor)
data_combo <- data_combo %>%
    mutate(sess_name = forcats::fct_relevel(sess_name, my_col_factor_order))

# Pull out non-character columns (these are usually data variables) vs. character columns (these are usually factors)
my_col_fact <- data_combo %>% dplyr::summarise_all(class) %>% stringr::str_detect("character|factor")
my_col_fact <- my_col_fact | colnames(data_combo) == "start_time_in_min" | colnames(data_combo) == "end_time_in_min"
my_colnames_factor <- colnames(data_combo[my_col_fact])
my_colnames_non_factor <- colnames(data_combo[!my_col_fact])

```



``` {r plot_analyse_loop, fig.width=4.5, fig.height=4, echo=FALSE, message=FALSE, error=TRUE}

exclude_cw_ccw <- TRUE
my_colour_set <- RColorBrewer::brewer.pal(9, 'Set1')
my_curr_var <- 1

for (i in 1:length(my_colnames_non_factor)) {

    # go thru each column variables
    my_colnames_test <- append(my_colnames_factor, my_colnames_non_factor[i])
    my_var <- my_colnames_non_factor[i]
    data_test <- data_combo[my_colnames_test] %>% rename(var = all_of(my_var))

    contains_cw_ccw = stringr::str_detect(my_var, "cw_") | stringr::str_detect(my_var, "ccw_")
    if (exclude_cw_ccw & contains_cw_ccw) {
        next
    } else {

        cat("\n###", my_curr_var, ":", my_var, "###\n")
        
        y_max = max(data_test$var)
        y_min = min(data_test$var)
        my_ylim <- ggplot2::ylim(y_min, y_max)

        data_plot <- data_test

        my_plot <- quick_lineplot_mean_sem_indi(
            data_plot, start_time_in_min, var, sess_name, MouseID) +
            xlab("time") +
            theme(axis.title.y = element_blank()) +
            ggtitle(my_var)
        my_plot <- my_plot +
            scale_colour_manual(values=my_colour_set[c(1, 5, 7)]) +
            scale_fill_manual(values=my_colour_set[c(1, 5, 7)]) +
            my_ylim

        print(my_plot)


        my_curr_var <- my_curr_var + 1
    }

}

```

